#!/bin/sh

set -ue

APP_ZIP_FILE="lastest-version.gz"
APP_LASTEST_DOWNLOAD_URL="https://github.com/poplax/ClangFormatter/releases/download/v1.0.0/${APP_ZIP_FILE}"
APP_TMP_DIR="code_style_tmp"
APP_FILENAME="ClangFormatter.app"

RED="\033[0;31m"
GREEN="\033[0;32m"

curl -o $APP_ZIP_FILE -LSk $APP_LASTEST_DOWNLOAD_URL 

echo "$APP_LASTEST_DOWNLOAD_URL"

if [ $? -ne 0 ]; then
	echo $RED"Failed."
	exit 0
fi

if [ ! -d $APP_TMP_DIR ]; then
	mkdir $APP_TMP_DIR
fi

tar -xzf $APP_ZIP_FILE -C $APP_TMP_DIR

# Install app

cd $APP_TMP_DIR	
cp -rf "$APP_FILENAME" "/Applications/"
open "/Applications/$APP_FILENAME"

if [ $? -eq 0 ]; then
	osascript -e 'quit app "ClangFormatter"'
fi

# Message.
echo ""
if [ $? -eq 0 ]; then
	echo $GREEN"***** Install Success."
	echo "Follow the step:"
	echo "System Preferences -> Extensions -> Xocde Source Editor -> ClangFormat"
else
	echo $GREEN"* Install Failed."
fi


